version: '3.8'

services:
  app:
    container_name: buildkor-web-v2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  tunnel:
    container_name: cloudflared-tunnel-v2
    image: cloudflare/cloudflared:latest
    restart: always
    # Cloudflare tünelinin 'app' servisine ulaşabilmesi için 
    # komutu dashboard ayarlarını ezecek şekilde veya yönlendirerek çalıştırıyoruz.
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - app
